title: "MaKaCo - Bioinformatic Consultants"
output_dir: "."
navbar:
  title: "MaKaCo - Bioinformatic Consultants"
  left:
    - text: "About us"
      href: about_us.html
    - text: "Services"
      href: services.html
    - text: "Publications"
      href: publications.html
output: 
    html_document:
       theme: cerulean
       toc: false